# Generated by Django 4.0 on 2021-12-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=125.99),
            preserve_default=False,
        ),
    ]
