# Generated by Django 4.0 on 2021-12-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_session_id_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='session_id',
            field=models.CharField(default='sdfsdfsdf', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(to='cart.CartItem'),
        ),
    ]
